spring.application.name=huganstorev2
# Config postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/hugan_dbv2
spring.datasource.username=postgres
spring.datasource.password=1234567
# Config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Port8080
server.port=${PORT:8080}

#config upload img
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CẤU HÌNH CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo_cloud}
cloudinary.api-key=${CLOUDINARY_API_KEY:123456789}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:secret123}
cloudinary.folder=${CLOUDINARY_FOLDER:hugan_uploads}

jwt.secret-key=${JWT_SECRET_KEY:c3VwZXJzZWNyZXRrZXlmb3JodWdhbnN0b3JlZmFzaGlvbjIwMjY=}
spring.config.import=optional:file:.env[.properties]