spring.application.name=huganstorev2

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/hugan_dbv2
spring.datasource.username=postgres
spring.datasource.password=1234567

# =========================
# JPA / HIBERNATE
# =========================

# Production không để Hibernate tự sửa database mỗi lần khởi động.
# Database trên Neon của bạn đã có bảng rồi.
spring.jpa.hibernate.ddl-auto=none

# Hibernate tự nhận PostgreSQL, không cần khai báo dialect thủ công.
spring.jpa.show-sql=false

# Không giữ EntityManager mở đến tận tầng web.
spring.jpa.open-in-view=true

# =========================
# HIKARI CONNECTION POOL
# =========================

# Render Free ít tài nguyên, không cần tạo pool lớn.
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0

# Không giữ connection rảnh không cần thiết.
spring.datasource.hikari.idle-timeout=30000

# Thời gian tối đa chờ lấy connection.
spring.datasource.hikari.connection-timeout=20000

# =========================
# SERVER
# =========================
server.port=${PORT:8080}

# =========================
# UPLOAD IMAGE
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================
# CLOUDINARY
# =========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo_cloud}
cloudinary.api-key=${CLOUDINARY_API_KEY:123456789}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:secret123}
cloudinary.folder=${CLOUDINARY_FOLDER:hugan_uploads}

# =========================
# JWT
# =========================
jwt.secret-key=${JWT_SECRET_KEY:c3VwZXJzZWNyZXRrZXlmb3JodWdhbnN0b3JlZmFzaGlvbjIwMjY=}

# =========================
# LOCAL .ENV
# =========================
spring.config.import=optional:file:.env[.properties]